# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: dra.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'dra.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tdra.proto\x12\x03\x64ra\"v\n\x11PullAndRunRequest\x12\x12\n\nimage_name\x18\x01 \x01(\t\x12\x0f\n\x07\x63ommand\x18\x02 \x03(\t\x12\x16\n\x0erestart_policy\x18\x03 \x01(\t\x12\x11\n\tmemory_gb\x18\x04 \x01(\x02\x12\x11\n\tcpu_cores\x18\x05 \x01(\x02\"\xa2\x01\n\x12PullAndRunResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x14\n\x0c\x63ontainer_id\x18\x02 \x01(\t\x12*\n\x0eworkload_state\x18\x03 \x01(\x0e\x32\x12.dra.WorkloadState\x12\x10\n\x08\x63pu_used\x18\x04 \x01(\x02\x12\x16\n\x0ememory_gb_used\x18\x05 \x01(\x02\x12\x0f\n\x07message\x18\x06 \x01(\t\",\n\x14StopContainerRequest\x12\x14\n\x0c\x63ontainer_id\x18\x01 \x01(\t\"U\n\x15StopContainerResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x1a\n\x12memory_gb_released\x18\x03 \x01(\x02*^\n\rWorkloadState\x12\x1e\n\x1aWORKLOAD_STATE_UNSPECIFIED\x10\x00\x12\x0b\n\x07STOPPED\x10\x01\x12\x0b\n\x07RUNNING\x10\x02\x12\x08\n\x04\x44ONE\x10\x03\x12\t\n\x05\x45RROR\x10\x04\x32\x98\x01\n\nDRAService\x12\x42\n\x0fPullAndRunImage\x12\x16.dra.PullAndRunRequest\x1a\x17.dra.PullAndRunResponse\x12\x46\n\rStopContainer\x12\x19.dra.StopContainerRequest\x1a\x1a.dra.StopContainerResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dra_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_WORKLOADSTATE']._serialized_start=436
  _globals['_WORKLOADSTATE']._serialized_end=530
  _globals['_PULLANDRUNREQUEST']._serialized_start=18
  _globals['_PULLANDRUNREQUEST']._serialized_end=136
  _globals['_PULLANDRUNRESPONSE']._serialized_start=139
  _globals['_PULLANDRUNRESPONSE']._serialized_end=301
  _globals['_STOPCONTAINERREQUEST']._serialized_start=303
  _globals['_STOPCONTAINERREQUEST']._serialized_end=347
  _globals['_STOPCONTAINERRESPONSE']._serialized_start=349
  _globals['_STOPCONTAINERRESPONSE']._serialized_end=434
  _globals['_DRASERVICE']._serialized_start=533
  _globals['_DRASERVICE']._serialized_end=685
# @@protoc_insertion_point(module_scope)
