# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import dra_pb2 as dra__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in dra_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DRAServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PullAndRunImage = channel.unary_unary(
                '/dra.DRAService/PullAndRunImage',
                request_serializer=dra__pb2.PullAndRunRequest.SerializeToString,
                response_deserializer=dra__pb2.PullAndRunResponse.FromString,
                _registered_method=True)
        self.StopContainer = channel.unary_unary(
                '/dra.DRAService/StopContainer',
                request_serializer=dra__pb2.StopContainerRequest.SerializeToString,
                response_deserializer=dra__pb2.StopContainerResponse.FromString,
                _registered_method=True)


class DRAServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def PullAndRunImage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopContainer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DRAServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PullAndRunImage': grpc.unary_unary_rpc_method_handler(
                    servicer.PullAndRunImage,
                    request_deserializer=dra__pb2.PullAndRunRequest.FromString,
                    response_serializer=dra__pb2.PullAndRunResponse.SerializeToString,
            ),
            'StopContainer': grpc.unary_unary_rpc_method_handler(
                    servicer.StopContainer,
                    request_deserializer=dra__pb2.StopContainerRequest.FromString,
                    response_serializer=dra__pb2.StopContainerResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dra.DRAService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dra.DRAService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DRAService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PullAndRunImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dra.DRAService/PullAndRunImage',
            dra__pb2.PullAndRunRequest.SerializeToString,
            dra__pb2.PullAndRunResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopContainer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dra.DRAService/StopContainer',
            dra__pb2.StopContainerRequest.SerializeToString,
            dra__pb2.StopContainerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
