create table if not exists public.jobs (
    id integer generated by default as identity primary key,
    image_id varchar not null,
    resource_requirements jsonb not null,
    image_name varchar not null,
    status varchar not null,
    created_at timestamp without time zone not null,
    updated_at timestamp without time zone not null
);

create table if not exists public.machines (
    machine_id varchar primary key,
    machine_name varchar not null,
    machine_type varchar not null,
    machine_created_at timestamp without time zone not null,
    machine_updated_at timestamp without time zone not null
);

insert into public.machines (
    machine_id,
    machine_name,
    machine_type,
    machine_created_at,
    machine_updated_at
)
values (
    'salah-macbook-pro',
    'Salah''s MacBook Pro',
    'MacBook Pro',
    '2026-04-09 23:39:48.868694',
    '2026-04-09 23:39:48.868694'
)
on conflict (machine_id) do update
set
    machine_name = excluded.machine_name,
    machine_type = excluded.machine_type,
    machine_created_at = excluded.machine_created_at,
    machine_updated_at = excluded.machine_updated_at;
