create table if not exists public.jobs (
    id integer generated by default as identity primary key,
    image_id varchar not null,
    username varchar,
    user_id integer,
    resource_requirements jsonb not null,
    image_name varchar not null,
    status varchar not null,
    created_at timestamp without time zone not null,
    updated_at timestamp without time zone not null
);

alter table if exists public.jobs
    add column if not exists username varchar;
alter table if exists public.jobs
    add column if not exists user_id integer;

create table if not exists public.deployment_users (
    id integer generated by default as identity primary key,
    username varchar not null unique,
    password_hash varchar not null,
    created_at timestamp without time zone not null,
    updated_at timestamp without time zone not null
);

alter table if exists public.jobs
    drop constraint if exists jobs_user_id_fkey;
alter table if exists public.jobs
    add constraint jobs_user_id_fkey
    foreign key (user_id)
    references public.deployment_users(id)
    on delete set null;

create table if not exists public.machines (
    machine_id varchar primary key,
    machine_name varchar not null,
    machine_type varchar not null,
    machine_created_at timestamp without time zone not null,
    machine_updated_at timestamp without time zone not null,
    dra_grpc_target text,
    available_gb double precision,
    available_cores double precision,
    last_heartbeat_at timestamp without time zone
);

create table if not exists public.job_queue (
    id              serial primary key,
    image_name      varchar not null,
    resource_requirements jsonb not null,
    machine_type    varchar,
    command         varchar,
    restart_policy  varchar,
    status          varchar not null default 'PENDING',
    scheduled_for   timestamptz,
    batch_id        varchar,
    container_id    varchar,
    machine_id      varchar,
    decision_reason text,
    decision_mode   varchar,
    error_message   text,
    created_at      timestamptz not null,
    updated_at      timestamptz not null
);

create table if not exists public.scheduler_decisions (
    id              serial primary key,
    job_queue_ids   integer[] not null,
    action          varchar not null,
    machine_id      varchar,
    delay_seconds   integer,
    batch_id        varchar,
    reason          text not null,
    mode            varchar not null,
    decided_at      timestamptz not null
);

insert into public.machines (
    machine_id,
    machine_name,
    machine_type,
    machine_created_at,
    machine_updated_at,
    dra_grpc_target,
    available_gb,
    available_cores,
    last_heartbeat_at
)
values (
    'salah-macbook-pro',
    'Salah''s MacBook Pro',
    'MacBook Pro',
    '2026-04-09 23:39:48.868694',
    '2026-04-09 23:39:48.868694',
    null,
    16.0,
    null,
    null
)
on conflict (machine_id) do update
set
    machine_name = excluded.machine_name,
    machine_type = excluded.machine_type,
    machine_created_at = excluded.machine_created_at,
    machine_updated_at = excluded.machine_updated_at,
    dra_grpc_target = excluded.dra_grpc_target,
    available_gb = excluded.available_gb,
    available_cores = excluded.available_cores,
    last_heartbeat_at = excluded.last_heartbeat_at;
